[book]
authors = ["Daria Sukhonina"]
language = "en"
multilingual = false
src = "src"
title = "zetanumbers book"

[output.html]
site-url = "/book/"
git-repository-url = "https://github.com/zetanumbers/book/tree/main"
edit-url-template = "https://github.com/zetanumbers/book/edit/main/{path}"

[rust]
edition = "2021"
