[book]
authors = ["Daria Sukhonina"]
language = "en"
multilingual = false
src = "src"
title = "zetanumbers book"

[output.html]
site-url = "/book/"
git-repository-url = "https://github.com/zetanumbers/book/tree/main"
edit-url-template = "https://github.com/zetanumbers/book/edit/main/{path}"
mathjax-support = true

[preprocessor.graphviz]
command = "mdbook-graphviz"
theme-colors = { foreground = "foreground" }
arguments = [
  "-Tsvg_inline",
  "-Gbgcolor=transparent",
  "-Ecolor=foreground",
  "-Efontcolor=foreground",
  "-Ncolor=foreground",
  "-Nfontcolor=foreground",
]

[preprocessor.footnote]

[rust]
edition = "2021"
